function (cpp_compiler_auto)
    if (NOT (CMAKE_C_COMPILER OR CMAKE_CXX_COMPILER) AND "$ENV{CC}$ENV{CXX}" STREQUAL "")
        find_program(clang_PATH "clang")
        find_program(clangxx_PATH "clang++")
        if (clang_PATH AND clangxx_PATH)
            set(CMAKE_C_COMPILER "${clang_PATH}" CACHE FILEPATH "")
            set(CMAKE_CXX_COMPILER "${clangxx_PATH}" CACHE FILEPATH "")
        else ()
            message(WARNING "could not find clang compiler")

            if (WIN32)
                find_program(cl_PATH "cl")
                if (cl_PATH)
                    set(CMAKE_C_COMPILER "${cl_PATH}" CACHE FILEPATH "")
                    set(CMAKE_CXX_COMPILER "${cl_PATH}" CACHE FILEPATH "")
                else ()
                    message(WARNING "could not find msvc compiler")
                endif ()
            endif ()
        endif ()
    endif ()
endfunction ()
